# Site settings
title: Nathan Struhs
email: nathanstruhs@gmail.com
#url: "http://nathanstruhs.github.com" # the base hostname & protocol for your site
github_username:  nathanstruhs

# Build settings
markdown: kramdown
baseurl: ""
exclude: ['README.md']
